


before_script:
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent)
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod 700 ~/.ssh/id_rsa
  - pwd
  - ssh-add





stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm -v
    - npm install
    - npm build

deploy:
  image: alpine
  stage: deploy
  script:
    - apk add --no-cache rsync
    - rsync -a build/ ci@wsu.party:build/
    