

stages:
  - build
  - deploy

build:
  image: node:6
  stage: build
  script:
    - npm -v
    - npm install
    - npm build

deploy:
  image: alpine
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - 'which ssh-agent || ( apk add --no-cache openssh-client )'
    - eval $(ssh-agent)
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - chmod 700 ~/.ssh/id_rsa
    - pwd
    - ssh-add
    - apk add --no-cache rsync
    - rsync -a --delete build/ ci@wsu.party:build/
    