image: node:6


before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo $CI_KEY
  - ssh-add <(echo $CI_KEY)
  - npm -v
  - npm install
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh



stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm build

deploy:
  stage: deploy
  script:
    - rsync -a build/ ci@wsu.party:build/
    